### PR TITLE
Enabling oc

### PR DESCRIPTION
**Pull request by dupontz**
Hey @ellyq, gustavo dupont from youtube comments here.

So far, it's been working with these changes. This bumps the memory performance and allows intel XTU.

Do you happen to know if it's possible to add menus to the bios. 

Like for example, NMODE [0,1,2]

### CODE REVIEW

**Comment by ellyq** [comment]
Hi, thanks!

I'm hoping to fix SPD Pointers in time for upstreaming, so that we can have working XMP support out of the box, but I don't think there's an EDK2 module that would allow you to adjust those settings at runtime.

That being said, StarLabs has [coreboot-configurator](https://github.com/StarLabsLtd/coreboot-configurator) that allows you to change certain paramaters without recompiling the firmware. I believe it should be possible to write something similar for memory setting!

**Comment by dupontz** [comment]
thanks, i was not expecting it to be merged so fast. we've learn that we need to set VrVoltageLimit and TdcCurrentLimit. It looks like we VR is not yet supported?

**Comment by ellyq** [comment]
It might depend on specific FSP settings, I will have a look at FspM tomorrow and see if I can figure out

**Comment by dupontz** [comment]
> It might depend on specific FSP settings, I will have a look at FspM tomorrow and see if I can figure out

Alright I will have a look as well

**Comment by ellyq** [comment]
Quick update before I head to sleep, you might want to have a look at following files:

`3rdparty/fsp/TigerLakeFspBinPkg/Docs/TigerLake_FSP_Integration_Guide.pdf`
`3rdparty/fsp/TigerLakeFspBinPkg/Client/Include/FspsUpd.h`
`src/mainboard/google/poppy/variants/baseboard/devicetree.cb`

I think this option won't work on TGL though, latest platform using is is KBL and headers clearly state that it's been deprecated:
```
/** Offset 0x059C - VR Voltage Limit
  PCODE MMIO Mailbox: VR Voltage Limit. DEPRECATED, Range is 0-7999mV.
**/
  UINT16                      VrVoltageLimit[5];
```

**Comment by dupontz** [comment]
I will need to dig more on [coreboot-configurator](https://github.com/StarLabsLtd/coreboot-configurator), it's throwing this: 
`nvramtool: CMOS option table not found in coreboot table.  Apparently, the coreboot installed on this system was built without selecting CONFIG_USE_OPTION_TABLE`

And I can't compile if I set that option.

**Pull request merged**
